version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/managerdb
    depends_on:
      - db
    volumes:
      - ./frontend:/frontend
      - ./backend:/app
    networks:
      - manager_net

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=managerdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - manager_net

volumes:
  postgres_data:


networks:
  manager_net:
